import { createSlice } from '@reduxjs/toolkit'

interface IdynamicData<T> {
  [key: string]: T
}

const data: IdynamicData<string> = {
  home_hero_t1: 'value1',
  home_hero_t2: 'value2',
  home_hero_t3: 'value3',
  home_hero_t4: 'value4',
  home_hero_t5: 'value5',
  home_perfect_car_t6: 'value6',
  home_perfect_car_t7: 'value7',
  home_perfect_car_t8: 'value8',
  home_perfect_car_t9: 'value9',
  home_perfect_car_t10: 'value10',

  home_sharing_market_title_1: 'sharing-market',
  home_sharing_market_item_1: 'A',
  home_sharing_market_item_2: 'B',
  home_sharing_maket_item_3: 'C',
  home_sharing_maket_item_4: 'D',
  home_sharing_maket_item_5: 'E',
  home_sharing_maket_item_6: 'F',
  home_sharing_maket_item_7: 'G',
  home_sharing_maket_item_8: 'H',

  home_step_title_1: 'Phan Ngoc Nam',
  home_step_heading_1: 'Phan Ngoc Nam v2',
  home_step_item_txt_1: 'Nam child',
  home_step_item_txt_2: 'sub title 1',
  home_step_item_txt_3: 'Luu so em di',
  home_step_item_txt_4: 'Khi nao ma co can con dau thi goi cho em',
  home_step_item_txt_5: 'Khong nho loi nua',
  home_step_item_txt_6: 'what do you ussually do after work?',

  home_q_and_a_title_txt_1: 'Questions mark?',
  home_q_and_a_label_txt_1: 'Hello guy!',
  home_q_and_a_desc_txt_1: 'Nice!',
  home_q_and_a_desc_txt_2: 'Keep it simple, stupid.',
  home_q_and_a_desc_txt_3: 'okela!',
  home_q_and_a_label_txt_2: 'nope!',
  home_q_and_a_desc_txt_4: 'Move forward!',
  home_q_and_a_desc_txt_5: '...',
  home_q_and_a_desc_txt_6: '...',
  home_q_and_a_label_txt_3: '...',
  home_q_and_a_desc_txt_7: '...',
  home_q_and_a_desc_txt_8: '...',
  home_q_and_a_desc_txt_9: '...',
  home_q_and_a_label_txt_4: '...',
  home_q_and_a_label_txt_10: '...',
  home_q_and_a_label_txt_11: '...',
  home_q_and_a_label_txt_12: '...',

  home_explore_txt_1: '...',
  home_explore_item_txt_1: '...',
  home_explore_item_txt_2: '...',

  drive_with_uber_q7a_title_1: '...',
  drive_with_uber_q7q_lbl_1: '...',
  drive_with_uber_q7q_content_1: '...',
  drive_with_uber_q7q_content_2: '...',
  drive_with_uber_q7q_content_3: '...',
  drive_with_uber_q7q_lbl_2: '...',
  drive_with_uber_q7q_content_4: '...',
  drive_with_uber_q7q_content_5: '...',
  drive_with_uber_q7q_content_6: '...',
  drive_with_uber_q7q_lbl_3: '...',
  drive_with_uber_q7q_content_7: '...',
  drive_with_uber_q7q_content_8: '...',
  drive_with_uber_q7q_content_9: '...',
  drive_with_uber_q7q_lbl_4: '...',
  drive_with_uber_q7q_content_10: '...',
  drive_with_uber_q7q_content_11: '...',
  drive_with_uber_q7q_content_12: '...',
  drive_with_uber_getStatedTitle_title_1: '...',
  drive_with_uber_getStatedTitle_btn_sub_lbl_1: '...',
  drive_with_uber_getStatedTitle_btn_lbl_1: '...',
  drive_with_uber_getStatedTitle_btn_sub_lbl_2: '...',
  drive_with_uber_getStatedTitle_btn_lbl_2: '...',
  drive_with_uber_getStatedTitle_sentence_1: '...',
  drive_with_uber_getStatedTitle_sentence_2: '...',
  drive_with_uber_getStatedTitle_sentence_3: '...',
  drive_with_uber_hero_img:
    'https://assets-global.website-files.com/5c16e90c8f6920b098f834e5/63d82ff7ba27e7ee16cce7de_dwuguest1tiny.jpeg ',
  drive_with_uber_hero_logo_unlock: '...',
  drive_with_uber_hero_logo_another: '...',
  drive_with_uber_hero_title_1: '...',
  drive_with_uber_hero_title_2: '...',
  drive_with_uber_hero_para_1: '...',
  drive_with_uber_hero_para_2: '...',
  drive_with_uber_hero_btn: '...',
  drive_with_uber_hero_link: '...',
  drive_with_uber_intro_img:
    'https://assets-global.website-files.com/5c16e90c8f6920b098f834e5/63f913e7a34806823acdff1a_ga-illustration-16.svg',
  drive_with_uber_intro_title_1: '...',
  drive_with_uber_intro_para_1: '...',
  drive_with_uber_intro_para_2: '...',
  drive_with_uber_perk_heading: '...',
  drive_with_uber_perk_title_1: '...',
  drive_with_uber_perk_desc_1: '...',
  drive_with_uber_perk_title_2: '...',
  drive_with_uber_perk_desc_2: '...',
  drive_with_uber_perk_title_3: '...',
  drive_with_uber_perk_desc_3: '...',
  drive_with_uber_perk_title_4: '...',
  drive_with_uber_perk_desc_4: '...',
  drive_with_uber_step_title: '...',
  drive_with_uber_step_heading: '...',
  drive_with_uber_step_img:
    'https://assets-global.website-files.com/5c16e90c8f6920b098f834e5/63cef76977f95804643dc7b4_howitworks-guest%20c-p-500.jpg',
  drive_with_uber_step_item_title_1: '...',
  drive_with_uber_step_item_sub_title_1: '...',
  drive_with_uber_step_item_title_2: '...',
  drive_with_uber_step_item_sub_title_2: '...',
  drive_with_uber_step_item_title_3: '...',
  drive_with_uber_step_item_sub_title_3: '...',

  partner_with_us_hero_img: '...',
  partner_with_us_hero_title: '...',
  partner_with_us_hero_content: '...',

  hosting_s1: 'value11',
  hosting_s2: 'value12',
  hosting_s3: 'value13',
  hosting_s4: 'value14',
  hosting_s5: 'value15',
  hosting_s6: 'value16',
  hosting_s7: 'value17',
  hosting_s8: 'value18',
  hosting_s9: 'value19',
  hosting_s10: 'value20',
  hosting_s11: 'value21',
  hosting_s12: 'value22',
  hosting_s13: 'value23',
  hosting_s14: 'value24',
  hosting_s15: 'value25',
  hosting_s16: 'value26',
  hosting_s17: 'value27',
  hosting_s18: 'value28',
  hosting_s19: 'value29'
}

const dataSlice = createSlice({
  name: 'dataSlice',
  initialState: data,
  reducers: {},
  extraReducers: (builder) => {}
})

export const {} = dataSlice.actions
const dataReducer = dataSlice.reducer
export default dataReducer
