const path = {
  home: '/',
  login: '/login',
  logout: '/logout',
  otp: '/otp',
  register: '/register',
  howitwork: '/our-solution/technology',
  howitworkconnect: '/our-solution/terms-conditions',
  hostrefernal: '/carshare/referral',
  aboutus: '/about-us/unlock-team',
  driveWithUber: '/partners/grab-be-drivers',
  partnerWithUs: '/partners/partner-with-us',
  sharACar: '/carshare/share-a-car',
  bookACar: '/carshare/book-a-car',
  hostCommunity: '/carshare/benefits',
  newsroom: 'newsroom/news',
  safetytrust: '/our-solution/safety-trust',
  test: '/test',
  insurance: '/solution/insurance',
  technology: '/solution/technology',
  termSolution: '/solution/term-condition',
  termCarShare: '/carshare/term-condition',
  benefit: '/car-share/benefit',
  partnerOur: '/partners/our-partners',
  blogs: '/newsroom/blogs',
  termPartner: '/newsroom/policy',
  eligibilitis: '/newsrooms/eligibilities',
  unlockTeam: '/about-us/unlock-team',
  contact: '/about-us/contact-us',
  moveServer: '/about-us/ourVision',
  hostBobus: '/host-bonus'
} as const

export default path
