const path = {
  home: '/',
  hostACar: '/host/xe',
  login: '/login',
  logout: '/logout',
  register: '/register',
  carUser: '/host/xe',
  howitwork: '/our-solution/technology',
  howitworkconnect: '/our-solution/terms-conditions',
  hostrefernal: '/carshare/referral',
  aboutus: '/about-us/unlock-team',
  driveWithUber: '/partners/grab-be-drivers',
  partnerWithUs: '/partners/partner-with-us',
  sharACar: '/carshare/share-a-car',
  bookACar: '/carshare/book-a-car',
  bookACarMobile: '/book-a-car/mobile/1',
  bookACarMobile2: '/book-a-car/mobile/2',
  bookACarMobile3: '/book-a-car/mobile/3',
  bookACarMobile4: '/book-a-car/mobile/4',
  bookACarMobile5: '/book-a-car/mobile/5',
  bookACarMobile6: '/book-a-car/mobile/6',
  bookACarMobile7: '/book-a-car/mobile/7',
  bookACarMobile8: '/book-a-car/mobile/8',
  bookACarMobile9: '/book-a-car/mobile/9',
  hostCommunity: '/carshare/benefits',
  newsroom: 'newsroom/news',
  safetytrust: '/our-solution/safety-trust',
  test: '/test',
  insurance: '/solution/insurance',
  technology: '/solution/technology',
  termSolution: '/solution/term-condition',
  termCarShare: '/carshare/term-condition',
  benefit: '/car-share/benefit',
  partnerOur: '/partners/our-partners',
  blogs: '/newsroom/blogs',
  termPartner: '/newsroom/policy',
  eligibilitis: '/newsrooms/eligibilities',
  unlockTeam: '/about-us/unlock-team',
  contact: '/about-us/contact-us',
  moveServer: '/about-us/ourVision',
  hostBobus: '/host-bonus',
  carMange: '/host/user/xe',
  upload: '/host/xe/upload-image'
} as const

export default path
