const path = {
  home: '/',
  login: '/admin/login',
  logout: '/admin/logout',
  register: '/register',
  howitwork: '/how-it-work',
  howitworkconnect: '/how-it-work/connect',
  hostrefernal: 'host-referral',
  aboutus: '/about-us',
  driveWithUber: '/drive-with-uber',
  partnerWithUs: '/partner-with-us',
  sharACar: '/host/share-a-car',
  hostCommunity: '/host/community',
  newsroom: '/news-room',
  safetytrust: '/how-it-work/safety-trust',
  test: '/test',
  insurance: '/solution/insurance',
  technology: '/solution/technology',
  termSolution: '/solution/term-condition',
  termCarShare: '/car-share/term-condition',
  benefit: '/car-share/benefit',
  partnerOur: '/partners/partnerOur',
  blogs: '/newsrooms/partnerOur',
  termPartner: '/newsrooms/term-condition',
  eligibilitis: '/newsrooms/eligibilities',
  unlockTeam: '/about-us/unlock-team',
  contact: '/about-us/contact',
  moveServer: '/about-us/move-to-server'
} as const

export default path
